python

diff --git a/0x00-python-hello_world/0-run b/0x00-python-hello_world/0-run
--- a/0x00-python-hello_world/0-run
+++ b/0x00-python-hello_world/0-run
@@ -1,16 +1,14 @@
 #!/bin/bash
 
 # Check if PYFILE environment variable is set
-if [ -z "$PYFILE" ]; then
-    echo "Error: PYFILE environment variable is not set."
-    exit 1
+if [-z "$PYFILE"]; then
+echo "Error: PYFILE environment variable is not set."
+exit 1
 fi
-
 # Check if the specified Python file exists
-if [ ! -f "$PYFILE" ]; then
-    echo "Error: File '$PYFILE' not found."
-    exit 1
+if [! -f "$PYFILE"]; then
+echo "Error: File '$PYFILE' not found."
+exit 1
 fi
-
 # Run the Python script
 python3 "$PYFILE"
